name: artifacts-upload and download
on:
  workflow_dispatch:
jobs:
  artifacts-upload:
    runs-on: ubuntu-latest
    steps:
      - name: create a log file artifact
        run: |
          echo "This is a log file from github actions" > logfile.txt

      - name: upload artifact
        uses:  actions/upload-artifact@v4
        with:
          name: logfile 
          path: logfile.txt
  artifact-download:
    runs-on: ubuntu-latest
    steps:
      - name: download logfile.txt
        uses: actions/download-artifact@v4
        with:
          name: logfile
      - name: use logfile in a step
        run: |
          cat logfile.txt
          
