name: caller build
on:   
  workflow_dispatch: 

jobs:
    build:
      uses: ./.github/workflows/reusable-build.yml
      with:
        app_name: "my-web-app"
        environment: "production"
      secrets: inherit
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: print build version
          run: | 
            echo "Deploying version: ${{ needs.build.outputs.build-version }}"
      
    
      
   
