name: github runners
on: 
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: system info 
        run: |
          echo "The Operating System is: ${{ runner.os}}"
          echo "The Runner's Hostname is: ${{ runner.name }}"
          echo "The Current User (Actor) is: ${{ github.actor }}"

      - name: pre-installed software version check
        run: |
          python --version
          docker --version
          git --version
          node --version
  job2:
    runs-on: macos-latest
    steps:
      - name: system info 
        run: |
          echo "runner os :  ${{ runner.os}}"
          echo "runner hostname :  ${{ runner.name }}"
          echo "user : ${{ github.actor }}"
  job3:
    runs-on: windows-latest
    steps:
      - name: system info 
        run: |
          Write-Output "The Operating System is:  ${{ runner.os}}"
          Write-Output "The Runner's Hostname is:  ${{ runner.name }}"
          Write-Output "The Current User running this job is: ${{ github.actor }}"
    
    
      
            
  
