name: github runners
on: 
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: system info 
        run: |
          echo "The Operating System is: $RUNNER_OS"
          echo "The Runner's Hostname is: $RUNNER_NAME"
          echo "The Current User (Actor) is: $GITHUB_ACTOR
  job2:
    runs-on: macos-latest
    steps:
      - name: system info 
        run: |
          echo "runner os : $(sw_vers -productVersion)"
          echo "runner hostname : $( hostname )"
          echo "user : $( whomai )"
  job3:
    runs-on: windows-latest
    steps:
      - name: system info 
        run: |
          Write-Output "The Operating System is: $env:RUNNER_OS"
          Write-Output "The Runner's Hostname is: $env:RUNNER_NAME"
          Write-Output "The Current User running this job is: $env:GITHUB_ACTOR"
    
    
      
            
  
