name: matrix build
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest]
        python-version: ['3.10', '3.11', '3.12']
        exclude:
          - os: windows-latest
            python-version: 3.10
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}

      - name: check python versions
        run: |
          python --version
          echo "Testing with Python ${{ matrix.python-version }}"
          echo "OS: ${{ matrix.os }}"

      - name: check fail-fast
        run: |
          if [ "${{ matrix.os}}" == "windows-latest"] && [ "${{matrix.python-version}}" == "3.12"]; then
             echo "failure...."
             exit 1
          fi
      - name: This runs if previous step succeeds
        run: echo "Success on ${{ matrix.os }} with Python ${{ matrix.python-version }}"
