name: reusable build
on: 
  workflow_call:
    inputs:
      app_name:
       description: 'enter the app name'
       required: true
       type: string
      environment:
       description: 'Environment to deploy to' 
       required: true
       default: 'staging'
       type: string

    secrets:
      DOCKER_TOKEN:
        description: 'DOCKER TOKEN'
        required: true
         
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: info
        run: echo "Building ${{ inputs.app_name }} for ${{inputs.environment }}"

      - name: docker token check
        run: |
          if [ -n "${{ secrets.DOCKER_TOKEN }}" ]; then
            echo "Docker token is set: true"
          else
            echo "Docker token is not set"
          fi
          
