name: secrets
on:
  workflow_dispatch:
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: check if secret exist
        run: |
          if [ -n "${{  secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else 
            echo "The string is not set: false"
          fi
          
      - name: secrets check
        run: echo "${{  secrets.MY_SECRET_MESSAGE }}"
