name: self-hosted runner
on: 
  workflow_dispatch: 
jobs:
  self-runner-check:
    runs-on:  my-linux-runner
    steps:
      - name: details of self-host runner
        run: |
          echo "HOSTNAME : $(hostname)"
          echo "PRESENT DIRECTORY: $(pwd)"
          cd /home/dikshith
          rm self_hosted
