name: paths and branch filters
on: 
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/**'
      - 'app/**'

jobs:
 paths:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v4
     -  run: echo "hello"
  
